### ISSUE TITLE
Broken update on OG Pebble

### ISSUE THREAD

**Issue by dabanhfreak** [JumpMaster/QuickAuth#37]
It seems you just updated the app?  I've been using it on my OG Pebble watch, and it's broken.  Both the watch app and the settings screen on my phone app simple crashes when I load them

**Comment by JumpMaster** [comment]
Hi,

What firmware version is your OG pebble on?

Kev

**Comment by dabanhfreak** [comment]
3.12.3, latest fw

**Comment by JumpMaster** [comment]
Thanks.

Can you give this version a test for me please.  The emulator is been a real PITA!

https://drive.google.com/file/d/0B_qIN0Xd80hCTjJKTEhkejltMGc/view?usp=sharing

Kev

**Comment by JumpMaster** [comment]
I've released 3.1 which fixes a bug. Waiting for confirmation it works on OG Pebbles. The emulator didn't crash but did report this issue.

**Comment by hgjensen** [comment]
Still not working after updating på 3.1.
App closes after a few seconds. Settings too.

**Comment by rsinger** [comment]
I have the same issue since the firmware update v3.12.3.  Lost all of my stored entries in the config menu in the Pebble app, too :(

Mine is also a Pebble Steel, everything the same as @hgjensen.  Using iOS 10.1.1 and Pebble app version 4.3, if that helps at all.

**Comment by JumpMaster** [comment]
There's no reason the codes should be deleted. I'm also having trouble finding any issues with the OG Pebble as the emulator works well. Any help would be appreciated!

**Comment by JumpMaster** [comment]
I've pushed 3.2 to the store.  Let me know if it resolves the issue!

**Comment by irgendwie** [comment]
Solves the issue(s) for me! Thank you very much!

**Comment by rsinger** [comment]
It works for me as well, thanks so much!

My codes are still gone (well, except one, oddly), but I can live with that now that it's working again!

**Comment by JumpMaster** [comment]
Hi all,

I've just pushed version 3.3 to the store which fixes the colour issue on multi-code view for black and white pebbles.  I guess this also happens on the Pebble 2.

Are there any outstanding issues?

Thanks,
Kev

**Comment by irgendwie** [comment]
@JumpMaster The color issue is gone, still the performance for multi-code view on the OG Pebble is pretty bad, I'll stick with the single-code view!

**Comment by JumpMaster** [comment]
@irgendwie 

Can you give this version a try.  I've halved the refresh speed to 16 frames per second.  30 may be OTT especially for the OG Pebble.

https://drive.google.com/file/d/0B_qIN0Xd80hCa3ljYTFucXpyRFE/view?usp=sharing

**Comment by irgendwie** [comment]
@JumpMaster Did test it - unfortunately the performance of multi-code view is still very poor. One can scroll up and down in the list of token, after multiple up/down it hangs at one token (still counting down the time) and you can only force quit it.
